export const ErrorCodes = {
	SomethingWentWrong: 1,
	InternalServerException: 2,
	InvalidEndpointException: 3,
	UnimplementedException: 4,
	HealthCheckFailedException: 5,
	UnauthorizedException: 6,
	TokenMissingException: 7,
	TokenExpiredException: 8,
	TokenVerificationException: 9,
	InvalidCredentialsException: 10,
	OTPGenerationException: 11,
	OTPExpiredException: 12,
	OTPVerificationException: 13,
	ForeignKeyViolationException: 14,
	DuplicateEntryException: 15,
	CreateFailedException: 16,
	UpdateFailedException: 17,
	RegistrationFailedException: 18,
	NotFoundException: 19,
	InvalidPropertiesException: 20,
	UnexpectedException: 21,
	TokenRefreshException: 22,
	LoginFailedException: 23,
	UserHadNoPermission: 24,
};